#!/bin/sh

# fortuner2 – show a fortune as a notification
# Copyright (C) 2012 Juhani Numminen <juhaninumminen0@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Set sh_word_split for zsh compatibility.
if [ -n "$ZSH_VERSION" ]; then
    setopt sh_word_split
fi

. gettext.sh

progname="fortuner2"
appname="Fortuner"
version="0.1.0"

TEXTDOMAIN="$progname"
export TEXTDOMAIN
TEXTDOMAINDIR="locale"
export TEXTDOMAINDIR

usagetext="$(eval_gettext "Usage: \${progname} [option...]

 -h show help message and exit
 -v print program name and version and exit
 
Everything after -- is passed to fortune program.")"

title="$(eval_gettext "Today's Fortune")"

fortunecmd="fortune"
notifycmd="notify-send \
--app-name=${appname} \
--icon=fortuner \
--urgency=low"

# Parse command line options.
while getopts hv opt; do
    case "$opt" in
        h)
            echo "$usagetext"
            exit 0
            ;;
        v)
            eval_gettext "\${progname} version \${version}"
            exit 0
            ;;
        \?)
            # getopts issues an error message.
            echo "$usagetext" >&2
            exit 1
            ;;
    esac
done

# Everything after -- is passed to fortune.
if [ "$1" = "--" ]; then
    shift
    fortunecmd="${fortunecmd} $@"
fi

# Send the notification.
$notifycmd "$title" "$($fortunecmd)"
